// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { CodecTypes as SqliteTypes } from '@prisma/orm-sqlite/adapter/codec-types';

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-sqlite/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-sqlite/contract/types';

export type StorageHash =
  StorageHashBase<'06bee6f29baa8eefffef2b1db6962af2c8f72a1a46912bd03d77216959fdd1a9'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'260b8608d1aacaf1f690779a6cff39a12947c599597c5ba464ca75b9e775df53'>;

export type CodecTypes = SqliteTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = Record<string, never>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'sql/float@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
      readonly 'sqlite/bigint@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
      readonly 'sqlite/bigintnumber@1': {
        readonly output: 'sqlite/real@1';
        readonly nullable: true;
      };
      readonly 'sqlite/integer@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
      readonly 'sqlite/real@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'sqlite/bigintnumber@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'sqlite/bigintnumber@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'sqlite/bigint@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'sqlite/bigint@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sqlite/bigint@1': { readonly output: 'sqlite/bigint@1'; readonly nullable: true };
      readonly 'sqlite/bigintnumber@1': {
        readonly output: 'sqlite/bigintnumber@1';
        readonly nullable: true;
      };
      readonly 'sqlite/blob@1': { readonly output: 'sqlite/blob@1'; readonly nullable: true };
      readonly 'sqlite/datetime@1': {
        readonly output: 'sqlite/datetime@1';
        readonly nullable: true;
      };
      readonly 'sqlite/integer@1': { readonly output: 'sqlite/integer@1'; readonly nullable: true };
      readonly 'sqlite/json@1': { readonly output: 'sqlite/json@1'; readonly nullable: true };
      readonly 'sqlite/real@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
      readonly 'sqlite/text@1': { readonly output: 'sqlite/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sqlite/bigint@1': { readonly output: 'sqlite/bigint@1'; readonly nullable: true };
      readonly 'sqlite/bigintnumber@1': {
        readonly output: 'sqlite/bigintnumber@1';
        readonly nullable: true;
      };
      readonly 'sqlite/blob@1': { readonly output: 'sqlite/blob@1'; readonly nullable: true };
      readonly 'sqlite/datetime@1': {
        readonly output: 'sqlite/datetime@1';
        readonly nullable: true;
      };
      readonly 'sqlite/integer@1': { readonly output: 'sqlite/integer@1'; readonly nullable: true };
      readonly 'sqlite/json@1': { readonly output: 'sqlite/json@1'; readonly nullable: true };
      readonly 'sqlite/real@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
      readonly 'sqlite/text@1': { readonly output: 'sqlite/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'sql/float@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sqlite/bigintnumber@1'; readonly nullable: true };
      readonly 'sqlite/bigint@1': {
        readonly output: 'sqlite/bigintnumber@1';
        readonly nullable: true;
      };
      readonly 'sqlite/bigintnumber@1': {
        readonly output: 'sqlite/bigintnumber@1';
        readonly nullable: true;
      };
      readonly 'sqlite/integer@1': {
        readonly output: 'sqlite/bigintnumber@1';
        readonly nullable: true;
      };
      readonly 'sqlite/real@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'sql/int@1': { readonly output: 'sqlite/bigint@1'; readonly nullable: true };
      readonly 'sqlite/bigint@1': { readonly output: 'sqlite/bigint@1'; readonly nullable: true };
      readonly 'sqlite/bigintnumber@1': {
        readonly output: 'sqlite/bigint@1';
        readonly nullable: true;
      };
      readonly 'sqlite/integer@1': { readonly output: 'sqlite/bigint@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly __unbound__: {
    readonly CalledNumber: {
      readonly id: CodecTypes['sqlite/text@1']['output'];
      readonly roundId: CodecTypes['sqlite/text@1']['output'];
      readonly value: CodecTypes['sqlite/integer@1']['output'];
      readonly order: CodecTypes['sqlite/integer@1']['output'];
      readonly calledAt: CodecTypes['sqlite/datetime@1']['output'];
    };
    readonly Cartela: {
      readonly id: CodecTypes['sqlite/text@1']['output'];
      readonly index: CodecTypes['sqlite/integer@1']['output'];
      readonly cells: CodecTypes['sqlite/text@1']['output'];
    };
    readonly PlayerCard: {
      readonly id: CodecTypes['sqlite/text@1']['output'];
      readonly roundId: CodecTypes['sqlite/text@1']['output'];
      readonly userId: CodecTypes['sqlite/text@1']['output'];
      readonly cartelaId: CodecTypes['sqlite/text@1']['output'];
      readonly marks: CodecTypes['sqlite/text@1']['output'];
      readonly disqualified: CodecTypes['sqlite/integer@1']['output'];
    };
    readonly Room: {
      readonly id: CodecTypes['sqlite/text@1']['output'];
      readonly code: CodecTypes['sqlite/text@1']['output'];
      readonly status: CodecTypes['sqlite/text@1']['output'];
      readonly createdAt: CodecTypes['sqlite/datetime@1']['output'];
      readonly hostUserId: CodecTypes['sqlite/text@1']['output'] | null;
    };
    readonly Round: {
      readonly id: CodecTypes['sqlite/text@1']['output'];
      readonly roomId: CodecTypes['sqlite/text@1']['output'];
      readonly status: CodecTypes['sqlite/text@1']['output'];
      readonly pattern: CodecTypes['sqlite/text@1']['output'];
      readonly hopInEndsAt: CodecTypes['sqlite/datetime@1']['output'] | null;
      readonly startingEndsAt: CodecTypes['sqlite/datetime@1']['output'] | null;
      readonly startedAt: CodecTypes['sqlite/datetime@1']['output'] | null;
      readonly endedAt: CodecTypes['sqlite/datetime@1']['output'] | null;
    };
    readonly User: {
      readonly id: CodecTypes['sqlite/text@1']['output'];
      readonly telegramId: CodecTypes['sqlite/text@1']['output'];
      readonly firstName: CodecTypes['sqlite/text@1']['output'];
      readonly username: CodecTypes['sqlite/text@1']['output'] | null;
      readonly photoUrl: CodecTypes['sqlite/text@1']['output'] | null;
      readonly createdAt: CodecTypes['sqlite/datetime@1']['output'];
    };
    readonly Win: {
      readonly id: CodecTypes['sqlite/text@1']['output'];
      readonly roundId: CodecTypes['sqlite/text@1']['output'];
      readonly userId: CodecTypes['sqlite/text@1']['output'];
      readonly playerCardId: CodecTypes['sqlite/text@1']['output'];
      readonly pattern: CodecTypes['sqlite/text@1']['output'];
      readonly claimedAt: CodecTypes['sqlite/datetime@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly __unbound__: {
    readonly CalledNumber: {
      readonly id: CodecTypes['sqlite/text@1']['input'];
      readonly roundId: CodecTypes['sqlite/text@1']['input'];
      readonly value: CodecTypes['sqlite/integer@1']['input'];
      readonly order: CodecTypes['sqlite/integer@1']['input'];
      readonly calledAt: CodecTypes['sqlite/datetime@1']['input'];
    };
    readonly Cartela: {
      readonly id: CodecTypes['sqlite/text@1']['input'];
      readonly index: CodecTypes['sqlite/integer@1']['input'];
      readonly cells: CodecTypes['sqlite/text@1']['input'];
    };
    readonly PlayerCard: {
      readonly id: CodecTypes['sqlite/text@1']['input'];
      readonly roundId: CodecTypes['sqlite/text@1']['input'];
      readonly userId: CodecTypes['sqlite/text@1']['input'];
      readonly cartelaId: CodecTypes['sqlite/text@1']['input'];
      readonly marks: CodecTypes['sqlite/text@1']['input'];
      readonly disqualified: CodecTypes['sqlite/integer@1']['input'];
    };
    readonly Room: {
      readonly id: CodecTypes['sqlite/text@1']['input'];
      readonly code: CodecTypes['sqlite/text@1']['input'];
      readonly status: CodecTypes['sqlite/text@1']['input'];
      readonly createdAt: CodecTypes['sqlite/datetime@1']['input'];
      readonly hostUserId: CodecTypes['sqlite/text@1']['input'] | null;
    };
    readonly Round: {
      readonly id: CodecTypes['sqlite/text@1']['input'];
      readonly roomId: CodecTypes['sqlite/text@1']['input'];
      readonly status: CodecTypes['sqlite/text@1']['input'];
      readonly pattern: CodecTypes['sqlite/text@1']['input'];
      readonly hopInEndsAt: CodecTypes['sqlite/datetime@1']['input'] | null;
      readonly startingEndsAt: CodecTypes['sqlite/datetime@1']['input'] | null;
      readonly startedAt: CodecTypes['sqlite/datetime@1']['input'] | null;
      readonly endedAt: CodecTypes['sqlite/datetime@1']['input'] | null;
    };
    readonly User: {
      readonly id: CodecTypes['sqlite/text@1']['input'];
      readonly telegramId: CodecTypes['sqlite/text@1']['input'];
      readonly firstName: CodecTypes['sqlite/text@1']['input'];
      readonly username: CodecTypes['sqlite/text@1']['input'] | null;
      readonly photoUrl: CodecTypes['sqlite/text@1']['input'] | null;
      readonly createdAt: CodecTypes['sqlite/datetime@1']['input'];
    };
    readonly Win: {
      readonly id: CodecTypes['sqlite/text@1']['input'];
      readonly roundId: CodecTypes['sqlite/text@1']['input'];
      readonly userId: CodecTypes['sqlite/text@1']['input'];
      readonly playerCardId: CodecTypes['sqlite/text@1']['input'];
      readonly pattern: CodecTypes['sqlite/text@1']['input'];
      readonly claimedAt: CodecTypes['sqlite/datetime@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly __unbound__: {
    readonly calledNumber: {
      readonly calledAt: CodecTypes['sqlite/datetime@1']['output'];
      readonly id: CodecTypes['sqlite/text@1']['output'];
      readonly order: CodecTypes['sqlite/integer@1']['output'];
      readonly roundId: CodecTypes['sqlite/text@1']['output'];
      readonly value: CodecTypes['sqlite/integer@1']['output'];
    };
    readonly cartela: {
      readonly cells: CodecTypes['sqlite/text@1']['output'];
      readonly id: CodecTypes['sqlite/text@1']['output'];
      readonly index: CodecTypes['sqlite/integer@1']['output'];
    };
    readonly playerCard: {
      readonly cartelaId: CodecTypes['sqlite/text@1']['output'];
      readonly disqualified: CodecTypes['sqlite/integer@1']['output'];
      readonly id: CodecTypes['sqlite/text@1']['output'];
      readonly marks: CodecTypes['sqlite/text@1']['output'];
      readonly roundId: CodecTypes['sqlite/text@1']['output'];
      readonly userId: CodecTypes['sqlite/text@1']['output'];
    };
    readonly room: {
      readonly code: CodecTypes['sqlite/text@1']['output'];
      readonly createdAt: CodecTypes['sqlite/datetime@1']['output'];
      readonly hostUserId: CodecTypes['sqlite/text@1']['output'] | null;
      readonly id: CodecTypes['sqlite/text@1']['output'];
      readonly status: CodecTypes['sqlite/text@1']['output'];
    };
    readonly round: {
      readonly endedAt: CodecTypes['sqlite/datetime@1']['output'] | null;
      readonly hopInEndsAt: CodecTypes['sqlite/datetime@1']['output'] | null;
      readonly id: CodecTypes['sqlite/text@1']['output'];
      readonly pattern: CodecTypes['sqlite/text@1']['output'];
      readonly roomId: CodecTypes['sqlite/text@1']['output'];
      readonly startedAt: CodecTypes['sqlite/datetime@1']['output'] | null;
      readonly startingEndsAt: CodecTypes['sqlite/datetime@1']['output'] | null;
      readonly status: CodecTypes['sqlite/text@1']['output'];
    };
    readonly user: {
      readonly createdAt: CodecTypes['sqlite/datetime@1']['output'];
      readonly firstName: CodecTypes['sqlite/text@1']['output'];
      readonly id: CodecTypes['sqlite/text@1']['output'];
      readonly photoUrl: CodecTypes['sqlite/text@1']['output'] | null;
      readonly telegramId: CodecTypes['sqlite/text@1']['output'];
      readonly username: CodecTypes['sqlite/text@1']['output'] | null;
    };
    readonly win: {
      readonly claimedAt: CodecTypes['sqlite/datetime@1']['output'];
      readonly id: CodecTypes['sqlite/text@1']['output'];
      readonly pattern: CodecTypes['sqlite/text@1']['output'];
      readonly playerCardId: CodecTypes['sqlite/text@1']['output'];
      readonly roundId: CodecTypes['sqlite/text@1']['output'];
      readonly userId: CodecTypes['sqlite/text@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly __unbound__: {
    readonly calledNumber: {
      readonly calledAt: CodecTypes['sqlite/datetime@1']['input'];
      readonly id: CodecTypes['sqlite/text@1']['input'];
      readonly order: CodecTypes['sqlite/integer@1']['input'];
      readonly roundId: CodecTypes['sqlite/text@1']['input'];
      readonly value: CodecTypes['sqlite/integer@1']['input'];
    };
    readonly cartela: {
      readonly cells: CodecTypes['sqlite/text@1']['input'];
      readonly id: CodecTypes['sqlite/text@1']['input'];
      readonly index: CodecTypes['sqlite/integer@1']['input'];
    };
    readonly playerCard: {
      readonly cartelaId: CodecTypes['sqlite/text@1']['input'];
      readonly disqualified: CodecTypes['sqlite/integer@1']['input'];
      readonly id: CodecTypes['sqlite/text@1']['input'];
      readonly marks: CodecTypes['sqlite/text@1']['input'];
      readonly roundId: CodecTypes['sqlite/text@1']['input'];
      readonly userId: CodecTypes['sqlite/text@1']['input'];
    };
    readonly room: {
      readonly code: CodecTypes['sqlite/text@1']['input'];
      readonly createdAt: CodecTypes['sqlite/datetime@1']['input'];
      readonly hostUserId: CodecTypes['sqlite/text@1']['input'] | null;
      readonly id: CodecTypes['sqlite/text@1']['input'];
      readonly status: CodecTypes['sqlite/text@1']['input'];
    };
    readonly round: {
      readonly endedAt: CodecTypes['sqlite/datetime@1']['input'] | null;
      readonly hopInEndsAt: CodecTypes['sqlite/datetime@1']['input'] | null;
      readonly id: CodecTypes['sqlite/text@1']['input'];
      readonly pattern: CodecTypes['sqlite/text@1']['input'];
      readonly roomId: CodecTypes['sqlite/text@1']['input'];
      readonly startedAt: CodecTypes['sqlite/datetime@1']['input'] | null;
      readonly startingEndsAt: CodecTypes['sqlite/datetime@1']['input'] | null;
      readonly status: CodecTypes['sqlite/text@1']['input'];
    };
    readonly user: {
      readonly createdAt: CodecTypes['sqlite/datetime@1']['input'];
      readonly firstName: CodecTypes['sqlite/text@1']['input'];
      readonly id: CodecTypes['sqlite/text@1']['input'];
      readonly photoUrl: CodecTypes['sqlite/text@1']['input'] | null;
      readonly telegramId: CodecTypes['sqlite/text@1']['input'];
      readonly username: CodecTypes['sqlite/text@1']['input'] | null;
    };
    readonly win: {
      readonly claimedAt: CodecTypes['sqlite/datetime@1']['input'];
      readonly id: CodecTypes['sqlite/text@1']['input'];
      readonly pattern: CodecTypes['sqlite/text@1']['input'];
      readonly playerCardId: CodecTypes['sqlite/text@1']['input'];
      readonly roundId: CodecTypes['sqlite/text@1']['input'];
      readonly userId: CodecTypes['sqlite/text@1']['input'];
    };
  };
};

export namespace Models {
  export type User = {
    id: CodecTypes['sqlite/text@1']['output'];
    telegramId: CodecTypes['sqlite/text@1']['output'];
    firstName: CodecTypes['sqlite/text@1']['output'];
    username: CodecTypes['sqlite/text@1']['output'] | null;
    photoUrl: CodecTypes['sqlite/text@1']['output'] | null;
    createdAt: CodecTypes['sqlite/datetime@1']['output'];
    hostedRooms: Room[];
    playerCards: PlayerCard[];
    wins: Win[];
    readonly [RelationKeys]?: 'hostedRooms' | 'playerCards' | 'wins';
  };
  export type Room = {
    id: CodecTypes['sqlite/text@1']['output'];
    code: CodecTypes['sqlite/text@1']['output'];
    status: CodecTypes['sqlite/text@1']['output'];
    createdAt: CodecTypes['sqlite/datetime@1']['output'];
    hostUserId: CodecTypes['sqlite/text@1']['output'] | null;
    host: User | null;
    rounds: Round[];
    readonly [RelationKeys]?: 'host' | 'rounds';
  };
  export type Round = {
    id: CodecTypes['sqlite/text@1']['output'];
    roomId: CodecTypes['sqlite/text@1']['output'];
    status: CodecTypes['sqlite/text@1']['output'];
    pattern: CodecTypes['sqlite/text@1']['output'];
    hopInEndsAt: CodecTypes['sqlite/datetime@1']['output'] | null;
    startingEndsAt: CodecTypes['sqlite/datetime@1']['output'] | null;
    startedAt: CodecTypes['sqlite/datetime@1']['output'] | null;
    endedAt: CodecTypes['sqlite/datetime@1']['output'] | null;
    calledNumbers: CalledNumber[];
    playerCards: PlayerCard[];
    room: Room;
    wins: Win[];
    readonly [RelationKeys]?: 'calledNumbers' | 'playerCards' | 'room' | 'wins';
  };
  export type Cartela = {
    id: CodecTypes['sqlite/text@1']['output'];
    index: CodecTypes['sqlite/integer@1']['output'];
    cells: CodecTypes['sqlite/text@1']['output'];
    playerCards: PlayerCard[];
    readonly [RelationKeys]?: 'playerCards';
  };
  export type PlayerCard = {
    id: CodecTypes['sqlite/text@1']['output'];
    roundId: CodecTypes['sqlite/text@1']['output'];
    userId: CodecTypes['sqlite/text@1']['output'];
    cartelaId: CodecTypes['sqlite/text@1']['output'];
    marks: CodecTypes['sqlite/text@1']['output'];
    disqualified: CodecTypes['sqlite/integer@1']['output'];
    cartela: Cartela;
    round: Round;
    user: User;
    wins: Win[];
    readonly [RelationKeys]?: 'cartela' | 'round' | 'user' | 'wins';
  };
  export type CalledNumber = {
    id: CodecTypes['sqlite/text@1']['output'];
    roundId: CodecTypes['sqlite/text@1']['output'];
    value: CodecTypes['sqlite/integer@1']['output'];
    order: CodecTypes['sqlite/integer@1']['output'];
    calledAt: CodecTypes['sqlite/datetime@1']['output'];
    round: Round;
    readonly [RelationKeys]?: 'round';
  };
  export type Win = {
    id: CodecTypes['sqlite/text@1']['output'];
    roundId: CodecTypes['sqlite/text@1']['output'];
    userId: CodecTypes['sqlite/text@1']['output'];
    playerCardId: CodecTypes['sqlite/text@1']['output'];
    pattern: CodecTypes['sqlite/text@1']['output'];
    claimedAt: CodecTypes['sqlite/datetime@1']['output'];
    playerCard: PlayerCard;
    round: Round;
    user: User;
    readonly [RelationKeys]?: 'playerCard' | 'round' | 'user';
  };
}

export declare const models: {
  User: Models.User;
  Room: Models.Room;
  Round: Models.Round;
  Cartela: Models.Cartela;
  PlayerCard: Models.PlayerCard;
  CalledNumber: Models.CalledNumber;
  Win: Models.Win;
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly __unbound__: {
        readonly id: '__unbound__';
        readonly kind: 'sqlite-namespace';
        readonly entries: {
          readonly table: {
            readonly calledNumber: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly roundId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly value: {
                  readonly nativeType: 'integer';
                  readonly codecId: 'sqlite/integer@1';
                  readonly nullable: false;
                };
                readonly order: {
                  readonly nativeType: 'integer';
                  readonly codecId: 'sqlite/integer@1';
                  readonly nullable: false;
                };
                readonly calledAt: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/datetime@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['roundId', 'value'] }];
              indexes: readonly [
                {
                  readonly name: 'calledNumber_roundId_idx_b7564116';
                  readonly prefix: 'calledNumber_roundId_idx';
                  readonly columns: readonly ['roundId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: '__unbound__' & NamespaceId;
                    readonly tableName: 'calledNumber';
                    readonly columns: readonly ['roundId'];
                  };
                  readonly target: {
                    readonly namespaceId: '__unbound__' & NamespaceId;
                    readonly tableName: 'round';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly cartela: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly index: {
                  readonly nativeType: 'integer';
                  readonly codecId: 'sqlite/integer@1';
                  readonly nullable: false;
                };
                readonly cells: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['index'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly playerCard: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly roundId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly userId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly cartelaId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly marks: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'sqlite/text@1', '[]'>;
                  };
                };
                readonly disqualified: {
                  readonly nativeType: 'integer';
                  readonly codecId: 'sqlite/integer@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'sqlite/integer@1', 0>;
                  };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [
                { readonly columns: readonly ['roundId', 'userId'] },
                { readonly columns: readonly ['roundId', 'cartelaId'] },
              ];
              indexes: readonly [
                {
                  readonly name: 'playerCard_roundId_idx_b7564116';
                  readonly prefix: 'playerCard_roundId_idx';
                  readonly columns: readonly ['roundId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'playerCard_userId_idx_a489d58a';
                  readonly prefix: 'playerCard_userId_idx';
                  readonly columns: readonly ['userId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'playerCard_cartelaId_idx_13e8608d';
                  readonly prefix: 'playerCard_cartelaId_idx';
                  readonly columns: readonly ['cartelaId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: '__unbound__' & NamespaceId;
                    readonly tableName: 'playerCard';
                    readonly columns: readonly ['roundId'];
                  };
                  readonly target: {
                    readonly namespaceId: '__unbound__' & NamespaceId;
                    readonly tableName: 'round';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: '__unbound__' & NamespaceId;
                    readonly tableName: 'playerCard';
                    readonly columns: readonly ['userId'];
                  };
                  readonly target: {
                    readonly namespaceId: '__unbound__' & NamespaceId;
                    readonly tableName: 'user';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: '__unbound__' & NamespaceId;
                    readonly tableName: 'playerCard';
                    readonly columns: readonly ['cartelaId'];
                  };
                  readonly target: {
                    readonly namespaceId: '__unbound__' & NamespaceId;
                    readonly tableName: 'cartela';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly room: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly code: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/datetime@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly hostUserId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['code'] }];
              indexes: readonly [
                {
                  readonly name: 'room_hostUserId_idx_13a2bd65';
                  readonly prefix: 'room_hostUserId_idx';
                  readonly columns: readonly ['hostUserId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: '__unbound__' & NamespaceId;
                    readonly tableName: 'room';
                    readonly columns: readonly ['hostUserId'];
                  };
                  readonly target: {
                    readonly namespaceId: '__unbound__' & NamespaceId;
                    readonly tableName: 'user';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly round: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly roomId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly pattern: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly hopInEndsAt: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/datetime@1';
                  readonly nullable: true;
                };
                readonly startingEndsAt: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/datetime@1';
                  readonly nullable: true;
                };
                readonly startedAt: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/datetime@1';
                  readonly nullable: true;
                };
                readonly endedAt: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/datetime@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'round_roomId_idx_fe51d647';
                  readonly prefix: 'round_roomId_idx';
                  readonly columns: readonly ['roomId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: '__unbound__' & NamespaceId;
                    readonly tableName: 'round';
                    readonly columns: readonly ['roomId'];
                  };
                  readonly target: {
                    readonly namespaceId: '__unbound__' & NamespaceId;
                    readonly tableName: 'room';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly user: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly telegramId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly firstName: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly username: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: true;
                };
                readonly photoUrl: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: true;
                };
                readonly createdAt: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/datetime@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['telegramId'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly win: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly roundId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly userId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly playerCardId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly pattern: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly claimedAt: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/datetime@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'win_roundId_idx_b7564116';
                  readonly prefix: 'win_roundId_idx';
                  readonly columns: readonly ['roundId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'win_userId_idx_a489d58a';
                  readonly prefix: 'win_userId_idx';
                  readonly columns: readonly ['userId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'win_playerCardId_idx_69f2cb48';
                  readonly prefix: 'win_playerCardId_idx';
                  readonly columns: readonly ['playerCardId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: '__unbound__' & NamespaceId;
                    readonly tableName: 'win';
                    readonly columns: readonly ['roundId'];
                  };
                  readonly target: {
                    readonly namespaceId: '__unbound__' & NamespaceId;
                    readonly tableName: 'round';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: '__unbound__' & NamespaceId;
                    readonly tableName: 'win';
                    readonly columns: readonly ['userId'];
                  };
                  readonly target: {
                    readonly namespaceId: '__unbound__' & NamespaceId;
                    readonly tableName: 'user';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: '__unbound__' & NamespaceId;
                    readonly tableName: 'win';
                    readonly columns: readonly ['playerCardId'];
                  };
                  readonly target: {
                    readonly namespaceId: '__unbound__' & NamespaceId;
                    readonly tableName: 'playerCard';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'sqlite';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly user: { readonly namespace: '__unbound__' & NamespaceId; readonly model: 'User' };
    readonly room: { readonly namespace: '__unbound__' & NamespaceId; readonly model: 'Room' };
    readonly round: { readonly namespace: '__unbound__' & NamespaceId; readonly model: 'Round' };
    readonly cartela: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'Cartela';
    };
    readonly playerCard: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'PlayerCard';
    };
    readonly calledNumber: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'CalledNumber';
    };
    readonly win: { readonly namespace: '__unbound__' & NamespaceId; readonly model: 'Win' };
  };
  readonly domain: {
    readonly namespaces: {
      readonly __unbound__: {
        readonly models: {
          readonly CalledNumber: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly roundId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly value: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/integer@1' };
              };
              readonly order: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/integer@1' };
              };
              readonly calledAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/datetime@1' };
              };
            };
            readonly relations: {
              readonly round: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Round';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['roundId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'calledNumber';
              readonly namespaceId: '__unbound__';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly roundId: { readonly column: 'roundId' };
                readonly value: { readonly column: 'value' };
                readonly order: { readonly column: 'order' };
                readonly calledAt: { readonly column: 'calledAt' };
              };
            };
          };
          readonly Cartela: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly index: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/integer@1' };
              };
              readonly cells: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
            };
            readonly relations: {
              readonly playerCards: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'PlayerCard';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['cartelaId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'cartela';
              readonly namespaceId: '__unbound__';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly index: { readonly column: 'index' };
                readonly cells: { readonly column: 'cells' };
              };
            };
          };
          readonly PlayerCard: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly roundId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly cartelaId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly marks: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly disqualified: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/integer@1' };
              };
            };
            readonly relations: {
              readonly cartela: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Cartela';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['cartelaId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly round: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Round';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['roundId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly user: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'User';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['userId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly wins: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Win';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['playerCardId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'playerCard';
              readonly namespaceId: '__unbound__';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly roundId: { readonly column: 'roundId' };
                readonly userId: { readonly column: 'userId' };
                readonly cartelaId: { readonly column: 'cartelaId' };
                readonly marks: { readonly column: 'marks' };
                readonly disqualified: { readonly column: 'disqualified' };
              };
            };
          };
          readonly Room: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly code: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/datetime@1' };
              };
              readonly hostUserId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
            };
            readonly relations: {
              readonly host: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'User';
                };
                readonly cardinality: 'N:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['hostUserId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly rounds: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Round';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['roomId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'room';
              readonly namespaceId: '__unbound__';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly code: { readonly column: 'code' };
                readonly status: { readonly column: 'status' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly hostUserId: { readonly column: 'hostUserId' };
              };
            };
          };
          readonly Round: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly roomId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly pattern: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly hopInEndsAt: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/datetime@1' };
              };
              readonly startingEndsAt: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/datetime@1' };
              };
              readonly startedAt: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/datetime@1' };
              };
              readonly endedAt: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/datetime@1' };
              };
            };
            readonly relations: {
              readonly calledNumbers: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'CalledNumber';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['roundId'];
                };
              };
              readonly playerCards: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'PlayerCard';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['roundId'];
                };
              };
              readonly room: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Room';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['roomId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly wins: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Win';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['roundId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'round';
              readonly namespaceId: '__unbound__';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly roomId: { readonly column: 'roomId' };
                readonly status: { readonly column: 'status' };
                readonly pattern: { readonly column: 'pattern' };
                readonly hopInEndsAt: { readonly column: 'hopInEndsAt' };
                readonly startingEndsAt: { readonly column: 'startingEndsAt' };
                readonly startedAt: { readonly column: 'startedAt' };
                readonly endedAt: { readonly column: 'endedAt' };
              };
            };
          };
          readonly User: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly telegramId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly firstName: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly username: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly photoUrl: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/datetime@1' };
              };
            };
            readonly relations: {
              readonly hostedRooms: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Room';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['hostUserId'];
                };
              };
              readonly playerCards: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'PlayerCard';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['userId'];
                };
              };
              readonly wins: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Win';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['userId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'user';
              readonly namespaceId: '__unbound__';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly telegramId: { readonly column: 'telegramId' };
                readonly firstName: { readonly column: 'firstName' };
                readonly username: { readonly column: 'username' };
                readonly photoUrl: { readonly column: 'photoUrl' };
                readonly createdAt: { readonly column: 'createdAt' };
              };
            };
          };
          readonly Win: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly roundId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly playerCardId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly pattern: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly claimedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/datetime@1' };
              };
            };
            readonly relations: {
              readonly playerCard: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'PlayerCard';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['playerCardId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly round: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Round';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['roundId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly user: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'User';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['userId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'win';
              readonly namespaceId: '__unbound__';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly roundId: { readonly column: 'roundId' };
                readonly userId: { readonly column: 'userId' };
                readonly playerCardId: { readonly column: 'playerCardId' };
                readonly pattern: { readonly column: 'pattern' };
                readonly claimedAt: { readonly column: 'claimedAt' };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly sql: {
      readonly enums: false;
      readonly foreignKeys: true;
      readonly jsonAgg: true;
      readonly lateral: false;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
  };
  readonly extensions: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
